spring:
  docker:
    compose:
      enabled: true

  datasource:
    url: jdbc:mysql://mysql:3306/product
    username: product
    password: product@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379
      password: klmin6394

decorator:
  datasource:
    p6spy:
      enable-logging: false

security :
  jwt :
    secret-key : 7ol3624yqKR9LbZ7kiMj5hvj4X9FQYKhroLAmrhudzQ=
    expiration-time : 900000
    refresh-expiration-time : 1800000
    exclude-path: /api/auth/login, /api/auth/refresh-token