spring :
  profiles :
    active : local
    group :
      local:
        - local
      docker:
        - docker
      prod:
        - prod
    include :
      - common

  jpa:
    open-in-view: false

---
spring :
  config :
    activate :
      on-profile : local
logging:
  config: classpath:log/log4j2-local.yml


---
spring :
  config :
    activate :
      on-profile : docker

logging:
  config: classpath:log/log4j2-docker.yml

---
spring :
  config :
    activate :
      on-profile : prod

logging:
  config: classpath:log/log4j2-prod.yml

